import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Página não encontrada</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <header>
        <h1>Página não encontrada</h1>
      </header>
      <main>
        <div className="container">
          <h1>{/* `${session?.user?.name}`' */}</h1>
        </div>
      </main>
      <footer>
        <div>
          <p />
        </div>
      </footer>
    </div>
  );
}
