import Head from 'next/head';
import LoginInput from '../components/LoginInput/LoginInput';

export default function Home() {
  return (
    <div>
      <Head>
        <title>SISTOCK</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <header>
        <div>
          <p />
        </div>
      </header>
      <main>
        <div className="container">
          <div className="login" id="login">
            <div className="form">
              <h1 className="titulo">SISTOCK</h1>
              <LoginInput />
              <LoginInput />
            </div>
          </div>
        </div>
      </main>
      <footer>
        <div>
          <p />
        </div>
      </footer>
    </div>
  );
}
