import Head from 'next/head';
import Login from '../components/Login/Login';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sistock</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className="container">
          <div className="login" id="login">
            <Login />
          </div>
        </div>
      </main>
    </div>
  );
}
