import { getSession } from 'next-auth/react';
import Head from 'next/head';
import Login from '../components/Login/Login';
import Navbar from '../components/Navbar/Navbar';

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (session) {
    return {
      redirect: {
        destination: '/',
        permanent: false
      }
    };
  }
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sistock</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header>
        <div>
          <p />
        </div>
      </header>
      <main>
        <Navbar></Navbar>
        <div className="container">
          <div className="login" id="login">
            <Login />
          </div>
        </div>
      </main>
      <footer>
        <div>
          <p />
        </div>
      </footer>
    </div>
  );
}
